### ISSUE TITLE
Using markdown tables leads to error "unknown tag: Caption"

### ISSUE THREAD

**Issue by fkohrt** [NMarkgraf/typography.py#5]
Compiling the following document with `pandoc -f markdown -t html5 -o test.html --filter=./typography.py test.md`

```Rmd
---
title: Test
---

  Right     Left     Center     Default
-------     ------ ----------   -------
     12     12        12            12
    123     123       123          123
      1     1          1             1

```

...leads to the error "unknown tag: Caption":

```
Traceback (most recent call last):
  File "./typography.py", line 494, in <module>
    main()
  File "./typography.py", line 488, in main
    doc=doc)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/panflute/io.py", line 266, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/panflute/io.py", line 239, in run_filters
    doc = load(input_stream=input_stream)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/panflute/io.py", line 59, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/srv/conda/envs/notebook/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/srv/conda/envs/notebook/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/srv/conda/envs/notebook/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/srv/conda/envs/notebook/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/panflute/elements.py", line 1532, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Caption
Error running filter ./typography.py:
Filter returned error status 1
```

**Comment by NMarkgraf** [comment]
I bet that you using the new pandoc release? - Panflute, which this filter depends on, isn't (currently) able to run with pandoc after 2.9.*. In 2.10 the major change was a change in AST. Please take also a look at: https://github.com/sergiocorreia/panflute/issues/142 for more information about this bug.

The only known workaround by now: Don't use pandoc 2.10 and later ...sorry.

**Comment by fkohrt** [comment]
> I bet that you using the new pandoc release?

You're right!

Thank you for the filter, I'll just wait then :)

**Comment by NMarkgraf** [comment]
No problem. -- I wish I could offer an other solution. If I would find time, I would try to move to a _lua_-filter instead of _Python-Panflute_-filter, but at the moment I've got no time for that step.

I will inform anybody if _panflute_ will be ready for 2.10+, but I guess that project is dead ....
